"""Project root discovery and Markdown file scanning."""

from __future__ import annotations

from pathlib import Path

from .constants import (
    INDEX_DIR_RELATIVE,
    KNOWLEDGE_DIR_NAME,
    SCHEMA_MARKER_FILE,
    TEMPLATE_RELATIVE_PATH,
)
from .models import Severity, ValidationIssue


class DiscoveryError(Exception):
    """Raised when project root cannot be resolved."""

    def __init__(self, message: str, rule_id: str = "K-DISC-001") -> None:
        super().__init__(message)
        self.rule_id = rule_id
        self.message = message


def is_project_root(path: Path) -> bool:
    return (path / SCHEMA_MARKER_FILE).is_file() and (path / KNOWLEDGE_DIR_NAME).is_dir()


def find_project_root(start_path: Path | None = None) -> Path:
    """Walk parents until 元数据规范.md and 01_知识库/ are both present."""
    current = (start_path or Path.cwd()).resolve()
    if current.is_file():
        current = current.parent
    for candidate in [current, *current.parents]:
        if is_project_root(candidate):
            return candidate
    raise DiscoveryError(
        f"Cannot find MATH-AI-LAB project root from {current}. "
        f"Expected both '{SCHEMA_MARKER_FILE}' and '{KNOWLEDGE_DIR_NAME}/'."
    )


def resolve_project_root(explicit_root: Path | None = None, start_path: Path | None = None) -> Path:
    if explicit_root is not None:
        root = explicit_root.expanduser().resolve()
        if not is_project_root(root):
            raise DiscoveryError(
                f"Invalid --root: {root}. "
                f"Expected both '{SCHEMA_MARKER_FILE}' and '{KNOWLEDGE_DIR_NAME}/'."
            )
        return root
    return find_project_root(start_path)


def knowledge_dir(project_root: Path) -> Path:
    return project_root / KNOWLEDGE_DIR_NAME


def template_path(project_root: Path) -> Path:
    return (project_root / TEMPLATE_RELATIVE_PATH).resolve()


def is_template_file(path: Path, project_root: Path) -> bool:
    try:
        return path.resolve() == template_path(project_root)
    except OSError:
        return False


def index_dir(project_root: Path) -> Path:
    return (project_root / INDEX_DIR_RELATIVE).resolve()


def is_under_generated_index(path: Path, project_root: Path) -> bool:
    """Exclude derived index Markdown generated by Knowledge Indexer."""
    try:
        path.resolve().relative_to(index_dir(project_root))
        return True
    except (OSError, ValueError):
        return False


def relative_to_root(path: Path, project_root: Path) -> str:
    try:
        return path.resolve().relative_to(project_root.resolve()).as_posix()
    except ValueError:
        return path.resolve().as_posix()


def discover_markdown_files(project_root: Path) -> tuple[list[Path], list[Path]]:
    """
    Recursively find *.md under 01_知识库/.

    Returns:
        (included_files, excluded_files) both stably sorted.

    Excluded (by explicit path, not by ID):
    - 知识库模板.md
    - 01_知识库/_索引/** (generated derived index)
    """
    base = knowledge_dir(project_root)
    if not base.is_dir():
        raise DiscoveryError(f"Knowledge directory not found: {base}")

    included: list[Path] = []
    excluded: list[Path] = []
    for path in sorted(base.rglob("*.md"), key=lambda p: relative_to_root(p, project_root)):
        resolved = path.resolve()
        if is_template_file(path, project_root) or is_under_generated_index(path, project_root):
            excluded.append(resolved)
        else:
            included.append(resolved)
    return included, excluded


def skipped_without_metadata_issue(relative_path: str) -> ValidationIssue:
    return ValidationIssue(
        severity=Severity.INFO,
        rule_id="K-DISC-INFO-001",
        message="Skipped Markdown without Knowledge metadata.",
        file=relative_path,
    )
